Add `name` method to `DeepClient`
deep-foundation/deeplinks pull request #193
Opened 2023-07-18 14:13 UTC by uselessgoddess

- add test for `name`

resolve https://github.com/deep-foundation/deeplinks/issues/192

2023-07-18 16:35 UTC, FreePhoenix888 requested changes

2023-07-18 16:35 UTC, FreePhoenix888 commented on imports/client.tsx
> +  async name(input: Link<number> | number): Promise<string | undefined> {
@Konard , @ivansglazunov , is it fine that signature sligthly different that in `nameLocal`?

2023-07-18 16:35 UTC, FreePhoenix888 commented on imports/client.tsx
> +    const {data: [self]} = await this.select(this.serializeWhere({
Why is `serializeWhere` used?

2023-07-18 16:35 UTC, FreePhoenix888 commented on imports/client.tsx
> +      to_id: { _eq: id },
```suggestion
      to_id: id,
```

2023-07-18 16:35 UTC, FreePhoenix888 commented on imports/client.tsx
> +      type: ['@deep-foundation/core', 'Contain'],
```suggestion
      type_id: {
        _id: ['@deep-foundation/core', 'Contain']
      },
```

2023-07-18 16:35 UTC, FreePhoenix888 commented on imports/client.tsx
> +    const {data: [self]} = await this.select(this.serializeWhere({
```suggestion
    const {data: [containLink]} = await this.select(this.serializeWhere({
```

2023-07-18 16:35 UTC, FreePhoenix888 commented on imports/client.tsx
> +    return self.value?.value;
```suggestion
    return containLink.value?.value;
```

2023-07-18 16:35 UTC, FreePhoenix888 commented on tests/client.tsx
> +    const {data: [newTypeTypeLink]} = await deepClient.insert({
```suggestion
    const {data: [{id: newTypeLinkId}]} = await deepClient.insert({
```

2023-07-18 16:35 UTC, FreePhoenix888 commented on tests/client.tsx
> +    });
```suggestion
    const typeName = "MyTypeName"
    const reservedLinkIds = await deep.reserve(2);
    const newTypeLinkId = reservedLinkIds.pop()!;
    const containLinkId = reservedLinkIds.pop()!;
    await deepClient.serial({
    operations: [
      {
        type: 'insert',
        table: 'links'
        objects: {
          id: newTypeLinkId,
          type_id: typeTypeLinkId,
        }
      },
      {
        type: 'insert',
        table: 'links',
        objects: {
          type_id: containTypeLinkId,
          from_id: deepClient.linkId,
          to_id: newTypeLinkId,
        }
      },
      {
        type: 'insert',
        table: 'strings',
        objects: {
          link_id: containLinkId,
          value: typeName
        }
      }
    ]
    });
```

2023-07-18 16:35 UTC, FreePhoenix888 commented on tests/client.tsx
> +    assert.equal(await deepClient.name(newTypeTypeLink.id), "MySuperType");
```suggestion
    assert.equal(await deepClient.name(newTypeLinkId), typeName);
```

2023-07-18 16:47 UTC, uselessgoddess commented on imports/client.tsx
> +  async name(input: Link<number> | number): Promise<string | undefined> {
What do u mean?

2023-07-18 16:49 UTC, uselessgoddess commented on imports/client.tsx
> +    const {data: [self]} = await this.select(this.serializeWhere({
I wasn't sure that `select` would understand without it. TypeScript analyzer isn't very happy

2023-07-18 16:50 UTC, uselessgoddess commented on imports/client.tsx
> +      type: ['@deep-foundation/core', 'Contain'],
It seriously doesn't work like `to_id: id`?

2023-07-18 16:50 UTC, uselessgoddess commented on imports/client.tsx
> +    const {data: [self]} = await this.select(this.serializeWhere({
Ok bro

2023-07-18 16:59 UTC, FreePhoenix888 commented on imports/client.tsx
> +    const {data: [self]} = await this.select(this.serializeWhere({
It will understand :)

2023-07-18 17:00 UTC, FreePhoenix888 commented on tests/client.tsx
> +    });
More readable

2023-07-18 17:07 UTC, uselessgoddess commented on tests/client.tsx
> +    });
😖

2023-07-19 09:29 UTC, FreePhoenix888 requested changes

2023-07-19 09:29 UTC, FreePhoenix888 commented on imports/client.tsx
> +    // @ts-ignore
What error is here if we remove ts-ignore?

2023-07-19 09:29 UTC, FreePhoenix888 commented on tests/client.tsx
> +      from_id: await deepClient.id('deep', 'admin'),
Why do not you use `deep.linkId`?

2023-07-19 09:29 UTC, FreePhoenix888 commented on tests/client.tsx
> +    });
```suggestion
```
We already insert this contain in by using serial above

2023-07-20 07:56 UTC, uselessgoddess commented on imports/client.tsx
> +    // @ts-ignore
Error like from [here](https://github.com/deep-foundation/deeplinks/pull/193/files#diff-8d81038d2496ce4bcab8b0652c97db0038d83354887e7611a95618182a1212c8R891-R892)

2023-07-20 07:57 UTC, uselessgoddess commented on tests/client.tsx
> +      from_id: await deepClient.id('deep', 'admin'),
Because by default it is `undefined` (it is easier to pass the link manually rather than to login client)

2023-07-20 07:58 UTC, uselessgoddess commented on tests/client.tsx
> +    });
My mistake

2023-07-21 17:23 UTC, FreePhoenix888 approved these changes

2023-07-21 17:23 UTC, merged